### ISSUE TITLE
NRE when HandlerEnd is null

### ISSUE THREAD

**Issue by ElektroKill** [Washi1337/Echo#101]
Hello,

I've recently come across a bug within the Echo's dnlib platform. When calling `ConstructSymbolicFlowGraph` on a `MethodDef` which has an `ExceptionHandler` that has HandlerEnd set to `null`. According to dnlib source code this happens when the handler ends at the end of the body.
https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/Emit/ExceptionHandler.cs#L30-L34
Apparently the same could theoretically happen with TryEnd:
https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/Emit/ExceptionHandler.cs#L13-L17

The solution to this would be to use the offset of the last instruction if the HandlerEnd or TryEnd properties are `null`.

Here is a small example file with such an exception handler and the code which causes the compiler to emit it. Only occurs with Release configuration.
[HandlerEndNull.zip](https://github.com/Washi1337/Echo/files/5902699/HandlerEndNull.zip)

Thanks in advance.

**Comment by Washi1337** [comment]
Note: this is probably not limited to just the dnlib platform back-end.
