### ISSUE TITLE
CilVirtualMachine modification of CurrentState

### ISSUE THREAD

**Issue by JPaja** [Washi1337/Echo#105]
When we want to emulate some methods from certain point, or we want to restore `CurrentState` to some prevous sate
we when we want to modify it

Current solution would be to clear `Stack` and repopulate it, and to overwrite existing values inside `Variables`
with new value or unknown value

my proposal is to eather make `CilVirtualMachine.CurrentState` settable
or to add `Remove` and `Clear` functions to `IVariableState`

**Comment by Washi1337** [comment]
Adding a `Remove` and `Clear` to the `IVariableState` sounds good.

Making the `CurrentState` writable can be nice for quick restoring of previous states with just a single assignment statement. Allowing this does mean that it needs to stay in sync with the state in the `CilExecutionContext`. This means that either on every instruction dispatch, a new `CilExecutionContext` has to be instantiated, or the current state property within that context must also be made writable. If the latter, then we need to update the current state after every instruction dispatch as well. It's possible, but not entirely sure yet if that's good design.

**Comment by Washi1337** [comment]
Superseded by the new implementation of the CIL VM (See #120)
