### ISSUE TITLE
Integer division and remainder algorithms

### ISSUE THREAD

**Issue by Washi1337** [Washi1337/Echo#19]
**Summary:**
Add, subtract and multiply are added to IntegerValue. What is missing is integer division, returning the dividend and remainder.

**Comment by mirec12590** [comment]
Could you please assign that issue to me? Thank you

**Comment by Washi1337** [comment]
Feel free to create a PR for it if you have an implementation :)

**Comment by zsr2531** [comment]
Partially implemented in #74. Remainder algorithm is missing.
