### ISSUE TITLE
Filtered exception handlers

### ISSUE THREAD

**Issue by Washi1337** [Washi1337/Echo#53]
**Summary:**
The CIL architecture supports exception handlers that are decorated with a filter block which is executed before control is transferred to the handler block. This filter block determines whether the virtual machine should enter the handler block, or pass on the exception to the upper scope. Currently, Echo has no way of representing these in terms of the `ExceptionHandlerRegion` and/or `ExceptionHandlerBlock`.

**Comment by zsr2531** [comment]
Possible idea: Extend `ExceptionHandlerRange` with two new ranges; a prologue and an epilogue range.
The code in the prologue range would run before the code in any of the handler regions.
And the code in the epilogue range would run before the scope is exited.

This would allow filtered execption handlers to be neatly supported using the prologue range.
