### ISSUE TITLE
Split basic blocks based on exception handler try regions

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Washi1337/Echo#69]
When creating CFGs of CIL code, there is (to my knowledge) no way to show control flow from a try block to a catch block. It would be convenient if there was a built-in way of splitting basic blocks so each block is either in or not in a try region.

**Comment by Washi1337** [comment]
Splitting basic blocks based on CIL exception handlers is already a built-in feature. It also puts nodes in the appropriate exception handler sub graphs, which can be accessed by either the `ControlFlowGraph.Regions`, or by using `node.GetParentExceptionHandler()`.

Using the AsmResolver back-end:
```csharp
MethodDefinition method = ...
var cfg = method.CilMethodBody.ConstructStaticFlowGraph();
```

Using the dnlib back-end:
```csharp
MethodDef method = ...
var cfg = method.ConstructStaticFlowGraph();
```

**Comment by HoLLy-HaCKeR** [comment]
That's exactly what I wanted, should have tried that in the first place. thanks!
