### ISSUE TITLE
Generate documentation automatically from XMLDOC.

### ISSUE THREAD

**Issue by zsr2531** [Washi1337/Echo#70]
**Summary**: The documentation of Echo is currently lacking. Another problem is that they all have to be written by hand for now.

**Suggestion**: Use some tool to automatically generate a website from the XML documentation found on public members.

**Possible candidates**:
- [docfx](https://github.com/dotnet/docfx)
- [wyam](https://github.com/Wyamio/Wyam)

**Comment by Washi1337** [comment]
DocFX was implemented
